spring.application.name=dailyfocus

# --- DB Setup ---
# connection to a local db instance
spring.datasource.url=jdbc:mysql://localhost:3307/dailyfocusdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
# set user name and password
spring.datasource.username=root
spring.datasource.password=secret
# automatically update the table based on the entities. no table drops
spring.jpa.hibernate.ddl-auto=update
# close the jpa entity manager when transaction ends
spring.jpa.open-in-view=false

# --- Swagger URL Setup ---
springdoc.swagger-ui.path=/docs

# --- JWT ---
# randomly generated: openssl rand -hex 32
spring.jwt.secret=2ba4e742fae67ba9567eb2bbd3ac41fb5d2efda639542c1a86147adeca7eed1a
# 900000 = 15 minutes token expiration
sping.jwt.expiration=900000
